/*
 * (C) Symbol Contributors 2021
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 */
import type { NextPage } from 'next';
import Head from 'next/head';
import { Container } from 'react-bootstrap';
import Banner from '@components/home/Banner/Banner';
import Middle from '@components/home/Middle/Middle';
import styles from './index.module.scss';
const Home: NextPage = () => {
    return (
        <Container fluid>
            <Head>
                <title>Garush</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section id="banner" className={styles.banner}>
                <Banner />
            </section>
            <section id="middle" className={styles.middle}>
                <Middle />
            </section>
        </Container>
    );
};

export default Home;
