/*
 * (C) Symbol Contributors 2021
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 *
 */
import type { GetServerSideProps, GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import { Container } from 'react-bootstrap';
import Banner from './home/Banner/Banner';
import Middle from './home/Middle/Middle';
import styles from './index.module.scss';
import { fetchCollections } from '@services/collectionService';
import { useEffect } from 'react';
import { Collection, setCollections } from '@store/collectionSlice';
import { useAppDispatch } from '@store/hooks';

interface HomePageProps {
    collections: Collection[];
}
const Home = (props: HomePageProps): JSX.Element => {
    const dispatch = useAppDispatch();
    useEffect(() => {
        if (props.collections?.length) {
            dispatch(setCollections(props.collections));
        }
    }, [dispatch, props.collections]);
    return (
        <Container fluid>
            <Head>
                <title>Garush</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section id="banner" className={styles.banner}>
                <Banner />
            </section>
            <section id="middle" className={styles.middle}>
                <Middle />
            </section>
        </Container>
    );
};
export const getServerSideProps: GetServerSideProps = async (context: GetServerSidePropsContext<any>) => {
    const collections = await fetchCollections();
    return {
        props: {
            collections,
        },
    };
};

export default Home;
