import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { useAppSelector } from '../hooks';

import type { AppState, AppThunk } from '../store';
import { fetchUserByEmail } from '../../services/userService';

export interface User {
    id: string;
    name: string;
    email: string;
    avatar?: string;
    walletAddress?: string;
    isActive?: boolean;
    loggedIn?: boolean;
}
export enum LoadingStatus {
    idle = 'idle',
    loading = 'loading',
    failed = 'failed',
}
export interface UserState {
    user?: User;
    status: LoadingStatus;
}

const initialState: UserState = {
    user: undefined,
    status: LoadingStatus.idle,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchUserAsync = createAsyncThunk('user/fetchUserByEmail', async (email: string) => {
    const response = await fetchUserByEmail(email);
    // The value we return becomes the `fulfilled` action payload
    return response;
});

export const userSlice = createSlice({
    name: 'user',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        // login: (state) => {
        //   // Redux Toolkit allows us to write "mutating" logic in reducers. It
        //   // doesn't actually mutate the state because it uses the Immer library,
        //   // which detects changes to a "draft state" and produces a brand new
        //   // immutable state based off those changes
        //   state.value += 1
        // },
        // decrement: (state) => {
        //   state.value -= 1
        // },
        // // Use the PayloadAction type to declare the contents of `action.payload`
        // incrementByAmount: (state, action: PayloadAction<number>) => {
        //   state.value += action.payload
        // },
        logout: (state) => {
            state.user = undefined;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchUserAsync.pending, (state) => {
                state.status = LoadingStatus.loading;
            })
            .addCase(fetchUserAsync.fulfilled, (state, action) => {
                state.status = LoadingStatus.idle;
                state.user = action.payload;
            })
            .addCase(fetchUserAsync.rejected, (state, ) => {
              state.status = LoadingStatus.failed;
              state.user = undefined;
          });
    },
});

export const { logout } = userSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`

// eslint-disable-next-line react-hooks/rules-of-hooks
export const selectUserState = () => useAppSelector((state: AppState) => state.user);

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectCount(getState())
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount))
//     }
//   }

export default userSlice.reducer;
